package raf.dsw.classycraft.app.observer.message;

public enum MessageType {
    ERROR, CANNOT_DELETE_PROJECT_EXPLORER, CANNOT_ADD_CHILD, NODE_NOT_SELECTED, MUST_INSERT_NAME, CANNOT_DELETE_FILE, RESOURCE_NOT_FOUND, COMPONENT_NOT_SELECTED, NAME_ALREADY_TAKEN;
}
